import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
<script 
  src="https://jaaxis-fe-git-new-features-alphasquad.vercel.app//chatbot.js" 
  data-chatbot-id="2ace3bb4e7c911f0b6ac7ae47d1978e4"
  data-assistant-id="3b3030d4e7c911f0b36b7ae47d1978e4"
  data-theme-color="#a7bb0a"
  data-avatar-image="https://jaaxis-staging.s3.ap-southeast-1.amazonaws.com/jaaxis-widget-logo.png"
  data-bubble-text=""
  data-width="400"
  data-height="680"
  data-position="right"
  data-show-on-mobile="false"
  async
></script>

      </body>
    </html>
  );
}
